/**
 * Created by yangyang on 2017/3/24.
 */

// 用户身份定义
const IDENTITY_SHOPKEEPER = 'shopkeeper'
const IDENTITY_PROMOTER= 'promoter'

// 各级代理名称
const AGENT_NONE = 0
const AGENT_PROVINCE = 1
const AGENT_CITY = 2
const AGENT_DISTRICT = 3
const AGENT_STREET = 4

// 推广员级别设定
const PROMOTER_LEVEL_1 = 'promoter_level_1'
const PROMOTER_LEVEL_2 = 'promoter_level_2'
const PROMOTER_LEVEL_3 = 'promoter_level_3'
const PROMOTER_LEVEL_4 = 'promoter_level_4'
const PROMOTER_LEVEL_5 = 'promoter_level_5'

module.exports = {
  IDENTITY_SHOPKEEPER: IDENTITY_SHOPKEEPER,
  IDENTITY_PROMOTER: IDENTITY_PROMOTER,

  AGENT_NONE: AGENT_NONE,
  AGENT_PROVINCE: AGENT_PROVINCE,
  AGENT_CITY: AGENT_CITY,
  AGENT_DISTRICT: AGENT_DISTRICT,
  AGENT_STREET: AGENT_STREET,

  PROMOTER_LEVEL_1: PROMOTER_LEVEL_1,
  PROMOTER_LEVEL_2: PROMOTER_LEVEL_2,
  PROMOTER_LEVEL_3: PROMOTER_LEVEL_3,
  PROMOTER_LEVEL_4: PROMOTER_LEVEL_4,
  PROMOTER_LEVEL_5: PROMOTER_LEVEL_5,
}